### ISSUE TITLE
python instructions

### ISSUE THREAD

**Issue by nagyrobi** [sysadminbr/migrate_pfsense#3]
Thank you for this script.

I use Ubuntu on my PC, and I have two versions of python installed:

With Python 3.10.12 I get:

```
$ python3 migrate_pfsense.py
  File "/home/xx/Programok/pfs-2-opns/migrate_pfsense-main/src/migrate_pfsense.py", line 167
    print(f'openvpn server "{vpn_config['description']}" already registered. skipping it.')
                                         ^^^^^^^^^^^
SyntaxError: f-string: unmatched '['
```
With Python 2.7.18 I get:

```
$ python2 migrate_pfsense.py
  File "migrate_pfsense.py", line 56
    print(f'route already registered on target firewall. skipping it')
                                                                    ^
SyntaxError: invalid syntax
```

**Comment by sysadminbr** [comment]
Can you please try it again?
I've fixed the wrong string interpolation.

**Comment by nagyrobi** [comment]
Same:

```
$ python3 migrate_pfsense.py
  File "/home/xx/Programok/pfs-2-opns/migrate_pfsense-main/src/migrate_pfsense.py", line 167
    print(f'openvpn server {vpn_config['description']} already registered. skipping it.')
                                        ^^^^^^^^^^^
SyntaxError: f-string: unmatched '['
$ python2 migrate_pfsense.py
  File "migrate_pfsense.py", line 56
    print(f'route already registered on target firewall. skipping it')
                                                                    ^
SyntaxError: invalid syntax
```

**Comment by sysadminbr** [comment]
ouch! 
nailed it. 
can you try again?

**Comment by nagyrobi** [comment]
Progress...
```
$ python3 migrate_pfsense.py
[+] firewall login sucessful
going next url: /index.php
[-] error adding route
{'result': 'failed', 'validations': {'route.network': 'Specify a valid network matching the gateways ip protocol.'}}
[+] route added successfuly
[+] route added successfuly
[+] route added successfuly
[-] error adding route
{'result': 'failed', 'validations': {'route.network': 'Specify a valid network matching the gateways ip protocol.'}}
[-] error adding route
{'result': 'failed', 'validations': {'route.network': 'Specify a valid network matching the gateways ip protocol.'}}
[+] ca authority imported successfuly
[+] ca authority imported successfuly
[+] ca authority imported successfuly
Traceback (most recent call last):
  File "/home/robi/Programok/pfs-2-opns/migrate_pfsense-main/src/migrate_pfsense.py", line 95, in <module>
    crt_encoded = certificate.find("crt").text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by sysadminbr** [comment]
Hi nagyrobi, 
can you share the <cert></cert> data section from your pfSense backup?
Looks like there's a empty certificate, or a mismatch in data fields.

**Comment by sysadminbr** [comment]
Fixed the python string formatting. 
the certificate issue could not be reproduced.
